Controllers/DiagnosisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Docteur.Models;
using Microsoft.AspNetCore.Mvc;

namespace Docteur.Controllers
{
    public class DiagnosisController : Controller
    {
        public IActionResult Index(string[] idParameter, string[] parameterValue, int age)
        {
            Person p = new Person();
            p.Age = age;
            p.AddParameter(idParameter, parameterValue);
            Doctor d = new Doctor();
            Diagnostic diagnostic = d.DiagnosePerson(p, null);
            return View(diagnostic);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Docteur.Models;

namespace Docteur.Controllers;
y b
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        CaracteristiqueCorps[] parametres = new CaracteristiqueCorps().Find(null, null).OfType<CaracteristiqueCorps>().ToArray();
        return View(parametres);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    CaracteristiqueCorps[] parametres = Model;
}

<!-- Banner Area Starts -->
    
    <!-- Banner Area End -->

    <!-- Feature Area Starts -->
    
    <!-- Feature Area End -->

    <!-- Welcome Area Starts -->
    
    <!-- Welcome Area End -->

    <!-- Department Area Starts -->
    
    <!-- Department Area Starts -->

    <!-- Patient Area Starts -->
    <section class="patient-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-top text-center">
                        <h2>Patient are saying</h2>
                        <p>Green above he cattle god saw day multiply under fill in the cattle fowl a all, living, tree word link available in the service for subdue fruit.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-5 offset-lg-1 align-self-center">
                    <div class="appointment-form text-center mt-5 mt-lg-0">
                        <h3 class="mb-5">Make a diagnosis</h3>
                        <form action="@Url.Action("Index", "Diagnosis")" style="color: white;" method="post">
                            <div class="form-group">
                                <label for="">Your Age</label>
                                <input type="number" name="age" required>
                            </div>
                            <fieldset>
                                <legend>Parameters (0 to 10)</legend>
                                @for (int i = 0; i < parametres.Length; i++)
                                {
                                    <div class="form-group">
                                        <label for="">@parametres[i].Nom</label>
                                        <input type="hidden" name="idParameter" value="@parametres[i].Id">
                                        <input type="text" name="parameterValue"  required> 
                                    </div>
                                }
                            </fieldset>
                            <button type="submit" class="template-btn">diagnose now</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Patient Area Starts -->

    <!-- Specialist Area Starts -->
    
    <!-- Specialist Area Starts -->

    <!-- Hotline Area Starts -->
    
    <!-- Hotline Area End -->

    <!-- News Area Starts -->
    
    <!-- News Area Starts -->